name: autotochka

services:
  autotochka-client:
    build:
      context: ../client
      dockerfile: ./docker/Dockerfile
    container_name: autotochka-client
    ports:
      - "5173:5173"
    volumes:
      - ../client:/app
      - /app/node_modules
