name: autotochka

services:
  autotochka-client:
    build:
      context: ../client
      dockerfile: ./docker/Dockerfile
    container_name: autotochka-client
    ports:
      - "5173:5173"
    volumes:
      - ../client:/app
      - /app/node_modules

  autotochka-server:
    build:
      context: ../server
      dockerfile: ./docker/Dockerfile
      args:
        HTTP_PROXY_URL: ${HTTP_PROXY_URL}
        HTTPS_PROXY_URL: ${HTTPS_PROXY_URL}
    container_name: autotochka-server
    ports:
      - "4000:3000"
    volumes:
      - ../server:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - HTTP_PROXY=${HTTP_PROXY_URL}
      - HTTPS_PROXY=${HTTPS_PROXY_URL}
      - http_proxy=${HTTP_PROXY_URL}
      - https_proxy=${HTTPS_PROXY_URL}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - autotochka-db

  autotochka-db:
    image: postgres:16-alpine
    container_name: autotochka-db
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: tochka
      POSTGRES_USER: tochka
      POSTGRES_PASSWORD: tochka
    volumes:
      - autotochka-db-data:/var/lib/postgresql/data

volumes:
  autotochka-db-data:
